# Generated by Django 5.1.6 on 2025-02-15 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False, verbose_name='match id')),
                ('team1', models.CharField(max_length=50, verbose_name='team1')),
                ('team2', models.CharField(max_length=50, verbose_name='team2')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lost', to=settings.AUTH_USER_MODEL, verbose_name='loser')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='update by')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_won', to=settings.AUTH_USER_MODEL, verbose_name='winner')),
            ],
        ),
    ]
