# Generated by Django 5.1.6 on 2025-02-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_user', to=settings.AUTH_USER_MODEL, verbose_name='team1'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_user', to=settings.AUTH_USER_MODEL, verbose_name='team2'),
        ),
    ]
