# Generated by Django 5.1.6 on 2025-02-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_matches_team1_alter_matches_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='loser',
        ),
    ]
