# Generated by Django 5.1.6 on 2025-02-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_matches_loser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarName', models.CharField(max_length=50, verbose_name='avatar name')),
                ('avatar', models.ImageField(upload_to='images/avatars/', verbose_name='avatar')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserAvatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.useravatar', verbose_name='avatar'),
        ),
    ]
